#
#  This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
# File :
/gui/addMenu g4file G4File
/gui/addButton g4file Continue continue
/gui/addButton g4file Exit "exit"
#
# Run menu :
/gui/addMenu run Run
/gui/addButton run "beamOn 1k" "/run/beamOn 1000"
/gui/addButton run "beamOn 10k" "/run/beamOn 10000"

#
# Gun menu :
/gui/addMenu gun Gun
/gui/addButton gun "50 MeV"  "/gun/energy 50 MeV"
/gui/addButton gun "12 GeV"   "/gun/energy 12 GeV"
/gui/addButton gun "4 GeV"  "/gun/energy 4 GeV"
/gui/addButton gun "e-"      "/gun/particle e-"
/gui/addButton gun "proton"  "/gun/particle proton"
/gui/addButton gun "proton"  "/gun/particle neutron"

#
#Verbose menu
/gui/addMenu verbose Verbose
/gui/addButton verbose "Lvl 0 - Silent" "/tracking/verbose 0"
/gui/addButton verbose "Lvl 1 - Min Info" "/tracking/verbose 1"
/gui/addButton verbose "Lvl 2 - Step Info" "/tracking/verbose 2"



#
# Vis menu :
/gui/addMenu vis Vis
/gui/addButton vis MINE "/control/execute vis.mac"
#
# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "Set style surface" "/vis/viewer/set/style surface"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wire"
/gui/addButton viewer "Refresh viewer" "/vis/viewer/refresh"
/gui/addButton viewer "Update viewer (interaction or end-of-file)" "/vis/viewer/update"
/gui/addButton viewer "Flush viewer (= refresh + update)" "/vis/viewer/flush"
/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"
#

